[[language]]
name = "cpp"
language-servers = ["clangd"]
formatter = ["clangd"]

[[language]]
name = "python"
language-servers = [
    {name = "pyright"},
    {name = "ruff"},
    {name = "mypy"}
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]
formatter = ["markdown-oxide"]
[[language]]
name = "toml"
roots = ["."]
language-servers = ["taplo"]

[[language]]
name = "nix"
auto-format = true
language-servers = ["nil"]
formatter = ["alejandra"]
[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log", "serve"]
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[[language]]
name = "go"
auto-format = true
language-servers = ["qmlls"]

[language-server.qmlls]
command = "qmlls"

[[language]]
name = "qml"
auto-format = true
language-servers = ["qmlls"]

[language-server.tailwindcss-ls]

command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
